var myArray = [
        {
          "Code": "618e22659cb091e632668eca",
          "index": 0,
          "balance": "2,499",
          "name": "Carolina Dodson",
          "AC_Name": "ZILLADYNE",
          "Opening_Bal": 2553,
          "company": "Agrani Bank Ltd",
          "Dr_Cr": "ONTALITY",
          "email": "carolinadodson@ontality.com",
          "phone": "+1 (822) 585-3136",
          "address": "569 Boulevard Court, Camas, American Samoa, 6156"
        },
        {
          "Code": "618e2265599e8842bd31d231",
          "index": 1,
          "balance": "1,726",
          "name": "Cabrera Larson",
          "AC_Name": "INVENTURE",
          "Opening_Bal": 1639,
          "company": "Bangladesh Development Bank Ltd.",
          "Dr_Cr": "TUBESYS",
          "email": "cabreralarson@tubesys.com",
          "phone": "+1 (904) 472-3043",
          "address": "793 Laurel Avenue, Gulf, Pennsylvania, 2295"
        },
        {
          "Code": "618e226560ce09860c30ba0f",
          "index": 2,
          "balance": "1,248",
          "name": "Bridgette Combs",
          "AC_Name": "MELBACOR",
          "Opening_Bal": 2534,
          "company": "Basic Bank Ltd",
          "Dr_Cr": "STRALUM",
          "email": "bridgettecombs@stralum.com",
          "phone": "+1 (862) 570-3369",
          "address": "640 Eastern Parkway, Lodoga, Marshall Islands, 3743"
        },
        {
          "Code": "618e22658aa2ca93179b7edc",
          "index": 3,
          "balance": "3,241",
          "name": "Candice Cameron",
          "AC_Name": "AUTOMON",
          "Opening_Bal": 1060,
          "company": "Janata Bank Ltd",
          "Dr_Cr": "VERTIDE",
          "email": "candicecameron@vertide.com",
          "phone": "+1 (985) 423-3807",
          "address": "332 Leonora Court, Dexter, Alabama, 239"
        },
        {
          "Code": "618e2265e1c4c6aa0d48bb71",
          "index": 4,
          "balance": "3,432",
          "name": "Kerry Gould",
          "AC_Name": "XIXAN",
          "Opening_Bal": 1321,
          "company": "Rupali Bank Ltd",
          "Dr_Cr": "IDETICA",
          "email": "kerrygould@idetica.com",
          "phone": "+1 (944) 582-2687",
          "address": "112 Croton Loop, Deltaville, Minnesota, 2783"
        },
        {
          "Code": "618e22657aab37ac69747c33",
          "index": 5,
          "balance": "3,270",
          "name": "Robles Underwood",
          "AC_Name": "APEXIA",
          "Opening_Bal": 1044,
          "company": "Sonali Bank Ltd",
          "Dr_Cr": "GLUID",
          "email": "roblesunderwood@gluid.com",
          "phone": "+1 (891) 400-3854",
          "address": "114 Myrtle Avenue, Campo, Georgia, 1821"
        },
        {
          "Code": "618e22653587684e61e263e0",
          "index": 6,
          "balance": "3,948",
          "name": "Benita Curtis",
          "AC_Name": "BITREX",
          "Opening_Bal": 2703,
          "company": "Private Commercial Banks",
          "Dr_Cr": "PARAGONIA",
          "email": "benitacurtis@paragonia.com",
          "phone": "+1 (956) 468-2250",
          "address": "676 Varick Avenue, Hachita, North Dakota, 9702"
        },
        {
          "Code": "618e226560e710d86ebab624",
          "index": 7,
          "balance": "1,437",
          "name": "Atkinson Harrell",
          "AC_Name": "ZOSIS",
          "Opening_Bal": 1398,
          "company": "AB Bank Ltd",
          "Dr_Cr": "BIOHAB",
          "email": "atkinsonharrell@biohab.com",
          "phone": "+1 (803) 441-3899",
          "address": "562 Seigel Street, Barrelville, Oklahoma, 9325"
        },
        {
          "Code": "618e226541929816d1e37ce6",
          "index": 8,
          "balance": "1,222",
          "name": "Ines Zimmerman",
          "AC_Name": "RECRITUBE",
          "Opening_Bal": 2689,
          "company": "Bangladesh Commerce Bank Ltd",
          "Dr_Cr": "NETUR",
          "email": "ineszimmerman@netur.com",
          "phone": "+1 (957) 561-2105",
          "address": "215 Aitken Place, Martell, Washington, 9371"
        },
        {
          "Code": "618e2265fede421803e8e646",
          "index": 9,
          "balance": "3,548",
          "name": "Juliette Giles",
          "AC_Name": "FIREWAX",
          "Opening_Bal": 1470,
          "company": "Bank Asia Ltd",
          "Dr_Cr": "MANUFACT",
          "email": "juliettegiles@manufact.com",
          "phone": "+1 (980) 435-2836",
          "address": "823 Olive Street, Deputy, Maine, 3195"
        },
        {
          "Code": "618e2265a4b94624b3e32a26",
          "index": 10,
          "balance": "2,044",
          "name": "Cline Fleming",
          "AC_Name": "CEDWARD",
          "Opening_Bal": 2241,
          "company": "Abdul Monem Limited",
          "Dr_Cr": "KYAGORO",
          "email": "clinefleming@kyagoro.com",
          "phone": "+1 (829) 495-3733",
          "address": "984 Aviation Road, Hatteras, Massachusetts, 2052"
        },
        {
          "Code": "618e2265b58de3b9b6633cc2",
          "index": 11,
          "balance": "2,340",
          "name": "Rose Landry",
          "AC_Name": "VIAGREAT",
          "Opening_Bal": 2553,
          "company": "A K Khan & Company",
          "Dr_Cr": "TRASOLA",
          "email": "roselandry@trasola.com",
          "phone": "+1 (826) 530-2553",
          "address": "229 Dodworth Street, Nelson, Wisconsin, 2815"
        },
        {
          "Code": "618e226541313228e820349a",
          "index": 12,
          "balance": "1,370",
          "name": "Michelle Stokes",
          "AC_Name": "ZILLACON",
          "Opening_Bal": 1644,
          "company": "Aarong",
          "Dr_Cr": "DRAGBOT",
          "email": "michellestokes@dragbot.com",
          "phone": "+1 (975) 582-3943",
          "address": "968 Langham Street, Enetai, California, 2714"
        },
        {
          "Code": "618e226552004082f89dd0ab",
          "index": 13,
          "balance": "2,280",
          "name": "Tasha Bray",
          "AC_Name": "EXOZENT",
          "Opening_Bal": 2795,
          "company": "ABC Radio",
          "Dr_Cr": "SLOFAST",
          "email": "tashabray@slofast.com",
          "phone": "+1 (966) 425-2855",
          "address": "293 Ferry Place, Juntura, New Hampshire, 519"
        },
        {
          "Code": "618e2265132b84174a96e657",
          "index": 14,
          "balance": "3,685",
          "name": "Brown Carey",
          "AC_Name": "SYBIXTEX",
          "Opening_Bal": 2839,
          "company": "Adamjee Jute Mills",
          "Dr_Cr": "CIRCUM",
          "email": "browncarey@circum.com",
          "phone": "+1 (985) 443-2045",
          "address": "296 Riverdale Avenue, Blodgett, Montana, 5841"
        },
        {
          "Code": "618e2265df5dcd32f7af427a",
          "index": 15,
          "balance": "3,604",
          "name": "Leanna Terry",
          "AC_Name": "RAMJOB",
          "Opening_Bal": 1853,
          "company": "GONKLE Ltd",
          "Dr_Cr": "ZERBINA",
          "email": "leannaterry@zerbina.com",
          "phone": "+1 (887) 433-2042",
          "address": "253 Butler Street, Mammoth, Idaho, 2112"
        },
        {
          "Code": "618e2265f97f8a5736e4174d",
          "index": 16,
          "balance": "3,268",
          "name": "Hannah Macias",
          "AC_Name": "DIGIAL",
          "Opening_Bal": 2268,
          "company": "Advanced Chemical Industries",
          "Dr_Cr": "VOIPA",
          "email": "hannahmacias@voipa.com",
          "phone": "+1 (954) 582-3898",
          "address": "720 Elliott Walk, Chical, Kentucky, 7379"
        },
        {
          "Code": "618e22659fb16c633b47a565",
          "index": 17,
          "balance": "1,881",
          "name": "Burch Berry",
          "AC_Name": "NURALI",
          "Opening_Bal": 1127,
          "company": "Agamee Prakashani",
          "Dr_Cr": "NIMON",
          "email": "burchberry@nimon.com",
          "phone": "+1 (854) 429-2734",
          "address": "982 Tillary Street, Ballico, West Virginia, 8690"
        },
        {
          "Code": "618e22657fc3c4b98a4a0d13",
          "index": 18,
          "balance": "2,694",
          "name": "Lambert Randolph",
          "AC_Name": "AQUAMATE",
          "Opening_Bal": 1293,
          "company": "Airtel Bangladesh",
          "Dr_Cr": "VIAGRAND",
          "email": "lambertrandolph@viagrand.com",
          "phone": "+1 (808) 513-3406",
          "address": "923 Schweikerts Walk, Allentown, Rhode Island, 8111"
        },
        {
          "Code": "618e22654ed0cc9e6423e25e",
          "index": 19,
          "balance": "2,461",
          "name": "Rodriquez Gentry",
          "AC_Name": "TASMANIA",
          "Opening_Bal": 1666,
          "company": "Akij",
          "Dr_Cr": "PUSHCART",
          "email": "rodriquezgentry@pushcart.com",
          "phone": "+1 (821) 485-3543",
          "address": "939 Indiana Place, Sultana, Louisiana, 3526"
        },
        {
          "Code": "618e226596597da4573cc1e0",
          "index": 20,
          "balance": "2,941",
          "name": "Toni Blackburn",
          "AC_Name": "ZOLAVO",
          "Opening_Bal": 1713,
          "company": "Alim Industries Limited",
          "Dr_Cr": "OPTICON",
          "email": "toniblackburn@opticon.com",
          "phone": "+1 (897) 517-2188",
          "address": "518 Bragg Street, Avoca, New Mexico, 402"
        },
        {
          "Code": "618e2265f68f0113b500909d",
          "index": 21,
          "balance": "1,949",
          "name": "Letitia Barlow",
          "AC_Name": "MONDICIL",
          "Opening_Bal": 2562,
          "company": "Amar Desh",
          "Dr_Cr": "ZAPHIRE",
          "email": "letitiabarlow@zaphire.com",
          "phone": "+1 (910) 495-2667",
          "address": "461 Kent Street, Statenville, Tennessee, 9812"
        },
        {
          "Code": "618e2265da6abb27b441ec24",
          "index": 22,
          "balance": "3,347",
          "name": "Rosalind Vargas",
          "AC_Name": "RECOGNIA",
          "Opening_Bal": 1596,
          "company": "Ananda Group",
          "Dr_Cr": "XOGGLE",
          "email": "rosalindvargas@xoggle.com",
          "phone": "+1 (964) 528-2499",
          "address": "907 Coyle Street, Chestnut, Missouri, 6528"
        },
        {
          "Code": "618e22651098ca4cdc874d3a",
          "index": 23,
          "balance": "1,775",
          "name": "Karen Slater",
          "AC_Name": "SUNCLIPSE",
          "Opening_Bal": 2675,
          "company": "Ananda Shipyard and Shipways",
          "Dr_Cr": "DOGNOST",
          "email": "karenslater@dognost.com",
          "phone": "+1 (926) 505-3506",
          "address": "685 Hegeman Avenue, Wilsonia, Hawaii, 2365"
        },
        {
          "Code": "618e226503b94c8c48776950",
          "index": 24,
          "balance": "1,524",
          "name": "Parks Estes",
          "AC_Name": "ROUGHIES",
          "Opening_Bal": 1745,
          "company": "Asian TV",
          "Dr_Cr": "UPDAT",
          "email": "parksestes@updat.com",
          "phone": "+1 (988) 575-3659",
          "address": "557 Polhemus Place, Iola, Northern Mariana Islands, 8382"
        },
        {
          "Code": "618e226571684b5fbaae9db3",
          "index": 25,
          "balance": "2,020",
          "name": "Yvette Hodge",
          "AC_Name": "ERSUM",
          "Opening_Bal": 1867,
          "company": "ASM Chemical Industries",
          "Dr_Cr": "SAVVY",
          "email": "yvettehodge@savvy.com",
          "phone": "+1 (950) 432-2253",
          "address": "263 Fleet Street, Sylvanite, Florida, 9734"
        },
        {
          "Code": "618e22653aaa312342026f55",
          "index": 26,
          "balance": "1,876",
          "name": "Church Vega",
          "AC_Name": "PLASTO",
          "Opening_Bal": 1839,
          "company": "ATN Bangla",
          "Dr_Cr": "TELEPARK",
          "email": "churchvega@telepark.com",
          "phone": "+1 (990) 425-3048",
          "address": "330 Manor Court, Jenkinsville, Puerto Rico, 4770"
        },
        {
          "Code": "618e2265fcc80c7bbbba7f19",
          "index": 27,
          "balance": "2,630",
          "name": "Hewitt Mitchell",
          "AC_Name": "ENQUILITY",
          "Opening_Bal": 1033,
          "company": "Bangladesh Bank",
          "Dr_Cr": "AQUAZURE",
          "email": "hewittmitchell@aquazure.com",
          "phone": "+1 (819) 460-2812",
          "address": "511 McKinley Avenue, Comptche, South Dakota, 6894"
        },
        {
          "Code": "618e2265c1aef068ecdb297b",
          "index": 28,
          "balance": "3,158",
          "name": "Charity Fisher",
          "AC_Name": "ZOMBOID",
          "Opening_Bal": 2291,
          "company": "Bangladesh Machine Tools Factory",
          "Dr_Cr": "ZENOLUX",
          "email": "charityfisher@zenolux.com",
          "phone": "+1 (970) 592-2889",
          "address": "297 Ryder Street, Wattsville, Oregon, 6305"
        },
        {
          "Code": "618e22658b80dd180506ad8d",
          "index": 29,
          "balance": "1,618",
          "name": "Tommie Merrill",
          "AC_Name": "EZENTIA",
          "Opening_Bal": 1863,
          "company": "Bangladesh Petroleum Corporation",
          "Dr_Cr": "SUREMAX",
          "email": "tommiemerrill@suremax.com",
          "phone": "+1 (975) 528-3984",
          "address": "264 Beverly Road, Day, Arkansas, 871"
        },
        {
          "Code": "618e22656b6b21baef66228d",
          "index": 30,
          "balance": "3,219",
          "name": "Buck Gross",
          "AC_Name": "TETAK",
          "Opening_Bal": 2869,
          "company": "Bangladesh Shipping Corporation",
          "Dr_Cr": "INSOURCE",
          "email": "buckgross@insource.com",
          "phone": "+1 (932) 514-2083",
          "address": "161 Henderson Walk, Gerton, Utah, 7735"
        },
        {
          "Code": "618e2265aad2cb5219c5fb85",
          "index": 31,
          "balance": "1,007",
          "name": "Bailey Higgins",
          "AC_Name": "MENBRAIN",
          "Opening_Bal": 2786,
          "company": "Banglalink",
          "Dr_Cr": "GEEKULAR",
          "email": "baileyhiggins@geekular.com",
          "phone": "+1 (976) 425-2618",
          "address": "210 Suydam Street, Genoa, Vermont, 8379"
        },
        {
          "Code": "618e22659fd18b8f13a1dbef",
          "index": 32,
          "balance": "1,796",
          "name": "Bobbie Schwartz",
          "AC_Name": "OMNIGOG",
          "Opening_Bal": 2665,
          "company": "Banglalion",
          "Dr_Cr": "BESTO",
          "email": "bobbieschwartz@besto.com",
          "phone": "+1 (808) 475-3160",
          "address": "437 Guider Avenue, Eureka, Virginia, 7974"
        },
        {
          "Code": "618e2265a9c0f5fff24830eb",
          "index": 33,
          "balance": "1,915",
          "name": "Nora Kelly",
          "AC_Name": "KONNECT",
          "Opening_Bal": 2896,
          "company": "Banglavision",
          "Dr_Cr": "ENOMEN",
          "email": "norakelly@enomen.com",
          "phone": "+1 (880) 541-3243",
          "address": "956 Aster Court, Grandview, Colorado, 8046"
        },
        {
          "Code": "618e2265ca8f61c0b9bf894e",
          "index": 34,
          "balance": "1,647",
          "name": "Torres Griffin",
          "AC_Name": "PRIMORDIA",
          "Opening_Bal": 1168,
          "company": "Bashundhara Group",
          "Dr_Cr": "SENMEI",
          "email": "torresgriffin@senmei.com",
          "phone": "+1 (868) 594-3697",
          "address": "305 Williams Court, Frystown, Alaska, 2952"
        },
        {
          "Code": "618e2265132912b707f231e8",
          "index": 35,
          "balance": "2,002",
          "name": "Trudy Glass",
          "AC_Name": "DUOFLEX",
          "Opening_Bal": 1974,
          "company": "Best Air",
          "Dr_Cr": "TALAE",
          "email": "trudyglass@talae.com",
          "phone": "+1 (965) 588-2531",
          "address": "451 Stockholm Street, Guthrie, South Carolina, 4386"
        },
        {
          "Code": "618e226527d3a173bd7f203f",
          "index": 36,
          "balance": "2,730",
          "name": "Allison Duffy",
          "AC_Name": "ZEROLOGY",
          "Opening_Bal": 2522,
          "company": "Beximco Pharma",
          "Dr_Cr": "TOURMANIA",
          "email": "allisonduffy@tourmania.com",
          "phone": "+1 (837) 466-3567",
          "address": "163 Willoughby Street, Elliott, Arizona, 6748"
        },
        {
          "Code": "618e226561bfe18a40b2554e",
          "index": 37,
          "balance": "3,145",
          "name": "Hurst Roth",
          "AC_Name": "EXOTECHNO",
          "Opening_Bal": 2092,
          "company": "Beximco",
          "Dr_Cr": "PROWASTE",
          "email": "hurstroth@prowaste.com",
          "phone": "+1 (976) 480-3293",
          "address": "147 Gotham Avenue, Woodlands, Michigan, 4496"
        },
        {
          "Code": "618e2265922b31f6036678a5",
          "index": 38,
          "balance": "2,699",
          "name": "Sara Guzman",
          "AC_Name": "PLUTORQUE",
          "Opening_Bal": 1891,
          "company": "Bikroy.com",
          "Dr_Cr": "AFFLUEX",
          "email": "saraguzman@affluex.com",
          "phone": "+1 (896) 498-2042",
          "address": "458 Centre Street, Chesapeake, Federated States Of Micronesia, 907"
        },
        {
          "Code": "618e22651341ed3e301245fb",
          "index": 39,
          "balance": "2,283",
          "name": "Berg Wallace",
          "AC_Name": "ZAGGLE",
          "Opening_Bal": 2749,
          "company": "Biman Bangladesh Airlines",
          "Dr_Cr": "ZENTRY",
          "email": "bergwallace@zentry.com",
          "phone": "+1 (909) 598-3923",
          "address": "291 Coleridge Street, Kimmell, Texas, 3164"
        },
        {
          "Code": "618e2265c1acf688a182ae4a",
          "index": 40,
          "balance": "1,298",
          "name": "Ellis Douglas",
          "AC_Name": "TERRAGEN",
          "Opening_Bal": 1208,
          "company": "Bismillah Airlines",
          "Dr_Cr": "TERAPRENE",
          "email": "ellisdouglas@teraprene.com",
          "phone": "+1 (943) 437-3649",
          "address": "872 Heath Place, Libertytown, Nevada, 5156"
        },
        {
          "Code": "618e2265e35f0e6d3917d776",
          "index": 41,
          "balance": "3,730",
          "name": "Brock Nichols",
          "AC_Name": "AEORA",
          "Opening_Bal": 2723,
          "company": "Bismillah Group",
          "Dr_Cr": "ZILLAR",
          "email": "brocknichols@zillar.com",
          "phone": "+1 (818) 575-3945",
          "address": "899 Irwin Street, Corriganville, North Carolina, 2340"
        },
        {
          "Code": "618e2265822db4ac9ce62fbd",
          "index": 42,
          "balance": "1,799",
          "name": "Slater Estrada",
          "AC_Name": "UBERLUX",
          "Opening_Bal": 2059,
          "company": "BRAC Bank Limited",
          "Dr_Cr": "VOLAX",
          "email": "slaterestrada@volax.com",
          "phone": "+1 (957) 567-3821",
          "address": "915 Boerum Street, Thatcher, Indiana, 1924"
        },
        {
          "Code": "618e226523f170aadbf53bf9",
          "index": 43,
          "balance": "2,613",
          "name": "Parsons Morton",
          "AC_Name": "PIVITOL",
          "Opening_Bal": 1298,
          "company": "BSRM",
          "Dr_Cr": "MITROC",
          "email": "parsonsmorton@mitroc.com",
          "phone": "+1 (952) 419-2978",
          "address": "557 Dunham Place, Blende, District Of Columbia, 2305"
        },
        {
          "Code": "618e2265069698d0ddd018ae",
          "index": 44,
          "balance": "3,155",
          "name": "Fowler Murray",
          "AC_Name": "COLLAIRE",
          "Opening_Bal": 2572,
          "company": "BTCL",
          "Dr_Cr": "NETPLODE",
          "email": "fowlermurray@netplode.com",
          "phone": "+1 (921) 409-2326",
          "address": "876 Norfolk Street, Waverly, New Jersey, 3684"
        },
        {
          "Code": "618e2265d451128d50b817cd",
          "index": 45,
          "balance": "2,793",
          "name": "Blanca Gonzalez",
          "AC_Name": "NIQUENT",
          "Opening_Bal": 1709,
          "company": "Building Technology & Ideas",
          "Dr_Cr": "BULLJUICE",
          "email": "blancagonzalez@bulljuice.com",
          "phone": "+1 (882) 469-3129",
          "address": "681 Anchorage Place, Whitestone, Palau, 1269"
        },
        {
          "Code": "618e2265a1b604850c325c17",
          "index": 46,
          "balance": "2,790",
          "name": "Mable Pate",
          "AC_Name": "LUNCHPOD",
          "Opening_Bal": 1634,
          "company": "City Group",
          "Dr_Cr": "ADORNICA",
          "email": "mablepate@adornica.com",
          "phone": "+1 (893) 405-3637",
          "address": "708 Hawthorne Street, Springdale, New York, 2333"
        },
        {
          "Code": "618e2265dee37ac36683e197",
          "index": 47,
          "balance": "3,103",
          "name": "Janette Mckay",
          "AC_Name": "MARVANE",
          "Opening_Bal": 2385,
          "company": "Citycell",
          "Dr_Cr": "CODAX",
          "email": "janettemckay@codax.com",
          "phone": "+1 (946) 440-3821",
          "address": "206 Quay Street, Allensworth, Guam, 9778"
        },
        {
          "Code": "618e2265f2432220c56dfee0",
          "index": 48,
          "balance": "3,301",
          "name": "Glover Hobbs",
          "AC_Name": "KROG",
          "Opening_Bal": 2785,
          "company": "Concord Group",
          "Dr_Cr": "CALCULA",
          "email": "gloverhobbs@calcula.com",
          "phone": "+1 (917) 432-2887",
          "address": "963 Madison Street, Utting, Kansas, 8858"
        },
        {
          "Code": "618e2265dc742e8a0875cdc7",
          "index": 49,
          "balance": "3,496",
          "name": "Kasey Perry",
          "AC_Name": "EXOSTREAM",
          "Opening_Bal": 1401,
          "company": "Confidence Group",
          "Dr_Cr": "SATIANCE",
          "email": "kaseyperry@satiance.com",
          "phone": "+1 (836) 594-3230",
          "address": "988 Clay Street, Maybell, Mississippi, 2890"
        },
        {
          "Code": "618e2265cfd1228699c6b92a",
          "index": 50,
          "balance": "2,860",
          "name": "Lacy Justice",
          "AC_Name": "BYTREX",
          "Opening_Bal": 2009,
          "company": "Dhaka Bank Limited",
          "Dr_Cr": "AUSTEX",
          "email": "lacyjustice@austex.com",
          "phone": "+1 (984) 593-3991",
          "address": "114 Reed Street, Balm, Delaware, 8178"
        },
        {
          "Code": "618e2265502fc9e0020ec10a",
          "index": 51,
          "balance": "2,351",
          "name": "Butler Shields",
          "AC_Name": "GLUKGLUK",
          "Opening_Bal": 1585,
          "company": "Eastern Bank Limited",
          "Dr_Cr": "COMSTAR",
          "email": "butlershields@comstar.com",
          "phone": "+1 (987) 401-2379",
          "address": "124 King Street, Bartley, Nebraska, 9723"
        },
        {
          "Code": "618e22651ed46f423311f91f",
          "index": 52,
          "balance": "3,735",
          "name": "Martin Sargent",
          "AC_Name": "CANDECOR",
          "Opening_Bal": 2187,
          "company": "Grameen Bank",
          "Dr_Cr": "ANDRYX",
          "email": "martinsargent@andryx.com",
          "phone": "+1 (869) 415-3384",
          "address": "420 Greenwood Avenue, Brewster, Wyoming, 8270"
        },
        {
          "Code": "618e226555a6bcd85aed8b66",
          "index": 53,
          "balance": "3,214",
          "name": "Cantu Browning",
          "AC_Name": "EGYPTO",
          "Opening_Bal": 2838,
          "company": "Ha-meem Group",
          "Dr_Cr": "ZYPLE",
          "email": "cantubrowning@zyple.com",
          "phone": "+1 (887) 427-2425",
          "address": "550 Cozine Avenue, Draper, Illinois, 4787"
        },
        {
          "Code": "618e226521d351b2ee9d58b4",
          "index": 54,
          "balance": "1,122",
          "name": "Cristina James",
          "AC_Name": "SOLAREN",
          "Opening_Bal": 2662,
          "company": "IDLC Securities Limited",
          "Dr_Cr": "DIGIGENE",
          "email": "cristinajames@digigene.com",
          "phone": "+1 (909) 409-3074",
          "address": "697 Granite Street, Castleton, Iowa, 8648"
        },
        {
          "Code": "618e2265e6113abe01b10083",
          "index": 55,
          "balance": "3,624",
          "name": "Gilbert Stanley",
          "AC_Name": "MUSIX",
          "Opening_Bal": 1351,
          "company": "Incepta Pharmaceuticals",
          "Dr_Cr": "PERKLE",
          "email": "gilbertstanley@perkle.com",
          "phone": "+1 (968) 592-2928",
          "address": "429 Randolph Street, Yogaville, Virgin Islands, 2633"
        }
  ]

    BuildTable(myArray)

     function BuildTable(data){
        var table = document.getElementById('myTable')
        for(var i=0; i<data.length; i++){
            var row = `
                  <tr>
                     <td>${data[i].index} </td>
                     <td>${data[i].name} </td>
                     <td>${data[i].company} </td>
                     <td>${data[i].email} </td>
                  </tr>`
            table.innerHTML += row
        }

  }